sudo: required
services:
  - docker

before_install:
  - docker build -t pohltho/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t pohltho/multi-client ./client
  - docker build -t pohltho/multi-nginx ./nginx
  - docker build -t pohltho/multi-server ./server
  - docker build -t pohltho/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take image and push them to docker CLI
  - docker push pohltho/multi-client
  - docker push pohltho/multi-nginx
  - docker push pohltho/multi-server
  - docker push pohltho/multi-worker
