version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev # not an real path just the name => path is in context
      context: ./server
    volumes:
    - /app/node_modules # do not try to overwrite this folder inside the container
    - ./server:/app
    environment:
      - REDIS_HOST=redis # just the name of the service => docker-compose magic
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
    - /app/node_modules # do not try to overwrite this folder inside the container
    - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules # do not try to overwrite this folder inside the container
      - ./worker:/app


